const messages = {
    en_US: {
        How_It_Works: "How It Works",
        Overview: "Overview",
        Support: "Support",
        You_have_been_support: "You have been support",
        Preview: "Preview",
        Close: "Close",
        Statistics: "Statistics",
        Posts_Count: "Posts Count",
        Not_Founded: "Not Founded",
        Post: "Post",
        Socials_Preview: "Socials Preview",
        Actions: "Actions",
        Load_posts: "Load posts",
        Limits: "Limits",
        Licence_Token: "Licence Token",
        Licence_Status: "Licence Status",
        Save: "Save",
        Count_requests: "Count of available requests:",
        out_of: "out of",
        Your_Limits: "Your Limits",
        Update_Limits: "Update Limits",

        Area_size: "Area size:",
        Logo: "Logo",
        Positions: "Positions",
        How_look: "How it will look",
        Background_Opacity: "Background Level Opacity",
        Opacity_Color: "Opacity Color",
        Other_settings: "Other settings",
        Positioning: "Positioning",
        Font_size: "Font size (em)",
        Font: "Font",
        Text_Color: "Text Color",
        Title_settings: "Title settings",
        Delete_Image: "Delete Image",
        Replace_Image: "Replace Image",
        Your_File: "Your File",
        Error_again: "Error, please try again",
        Choose_File: "Choose File",
        or: "or",
        Drop_file: "Drop your file here",
        Upload_logo: "Upload image for logo",
        Title_enable: "Title enable",
        Logo_enable: "Logo enable",
        Preview_Settings: "Preview Settings",
        Twitter: "Twitter",
        Facebook: "Facebook",
        Vkontakte: "Vkontakte",
        Social_Network: "Social Network",
        Settings: "Settings",
    },
    ru_RU: {
        How_It_Works: "Как это работает",
        Overview: "Панель",
        Support: "Поддержка",
        You_have_been_support: "У вас активна техническая поддержка",
        Preview: "Превью",
        Close: "Закрыть",
        Statistics: "Записи",
        Posts_Count: "Количество",
        Not_Founded: "Ничего не найдено",
        Post: "Запись",
        Socials_Preview: "Превью",
        Actions: "Действия",
        Load_posts: "Загрузить посты",
        Limits: "Лимиты",
        Licence_Token: "Лицензионный ключ",
        Licence_Status: "Статус лицензии",
        Save: "Сохранить",
        Count_requests: "Количество доступных запросов",
        out_of: "из",
        Your_Limits: "Доступный лимит",
        Update_Limits: "Докупить лимит",

        Area_size: "Размер",
        Logo: "Лого",
        Positions: "Позиция",
        How_look: "Как будет выглядеть",
        Background_Opacity: "Прозрачность фона",
        Opacity_Color: "Просрачность цвета",
        Other_settings: "Другие настройки",
        Positioning: "Позиция",
        Font_size: "Размер шрифта (em)",
        Font: "Шрифт",
        Text_Color: "Цвет текста",
        Title_settings: "Настройки заголовка",
        Delete_Image: "Удалить лого",
        Replace_Image: "Заменить лого",
        Your_File: "Файл",
        Error_again: "Ошибка попробуйте еще раз",
        Choose_File: "Выберите файл",
        or: "или",
        Drop_file: "Перенесите файл сюда",
        Upload_logo: "Загрузите изображение для логотипа",
        Title_enable: "Включить заголовок",
        Logo_enable: "Включить логотип",
        Preview_Settings: "Настройки превью",
        Twitter: "Twitter",
        Facebook: "Facebook",
        Vkontakte: "Вконтакте",
        Social_Network: "Социальные сети",
        Settings: "Настройки",
    },
  };

export default messages;